[env]
TERM = "xterm-256color"

[general]
live_config_reload = true

[window]
dimensions.columns = 120
dimensions.lines = 38
padding.x = 10
padding.y = 10
decorations = "Full"
opacity = 0.95

[font]
size = 12
normal.family = "FiraCode Nerd Font"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[colors]
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

[colors.selection]
background = '#7aa2f7'
